exhaust stripe search data and expiring cards function
renderbox/django-vendor pull request #324
Opened 2022-11-10 21:32 UTC by fahzee1

- Search was only returning 100, function now exhausts the entire list
- Expiring cc's function

2022-11-11 15:36 UTC, rhimmelbauer requested changes
Looks ok, but it seems to excesive to get al customers and check them individually to check if their card is going to expires.


I noticed that stripe does have an event trigger when a card is going to expire in one month.


I would create an API endpoint to catch that event, and on our side we trigger a django signal eg: `card_expire_warning` to create the notification. 


That way we avoid having to run that long query. 


Look at:
- `vendor/api/v1/stripe/views.py` for endpoint examples.
- You can follow this instructions to test you webhooks: https://stripe.com/docs/webhooks/test

2022-11-14 17:54 UTC, fahzee1 commented on vendor/stripe_signals.py
> +
Had to be put in its own file for reason in the comment above

2022-11-14 18:04 UTC, rhimmelbauer requested changes
@fahzee1, merged develop to your current branch and move the contents you have to `vendor/signals/stripe_signals.py` file and remove the `stripe_signals.py` file you created

2022-11-14 18:09 UTC, fahzee1 commented on vendor/api/v1/stripe/views.py
> +        if not self.is_incoming_event_correct(self.event, StripeEvents.INOVICE_PAYMENT_SUCCEEDED):
Oh damn I thought I committed that change

2022-11-14 23:38 UTC, rhimmelbauer commented on vendor/processors/base.py
> +customer_source_expiring = django.dispatch.Signal()
lets keep it consistent and change the name to vendor_customer_card_expiring

2022-11-14 23:41 UTC, rhimmelbauer requested changes
create a function in the base processor that is responsible of triggering the vendor_customer_card_expiring signal. 

Remove the import on the stripe_processor.py file

2022-11-14 23:41 UTC, rhimmelbauer commented on vendor/processors/stripe_processor.py
> +        customer_source_expiring.send(sender=self.__class__, site_pk=site.pk, email=email)
Move this to the base processor

2022-11-15 17:23 UTC, rhimmelbauer approved these changes

2022-11-15 18:01 UTC, merged